name: self-awakening

on:
    schedule:
        - cron: '*/5 * * * *'

jobs:
    Keep-Alive:
        runs-on:
            ubuntu-latest
        
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '18'
        
            - name: Install dependencies
              run: npm install node-fetch
            
            - name: Cron job start
              run: node ./tools/keepAlive.js

